apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-configuracao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-configuracao
  template:
    metadata:
      labels:
        app: app-configuracao
    spec:
      containers:
        - name: app-config
          image: rrochati/app-variaveis-ambiente:v2
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
          - secretRef:
            name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app-configuracao-svc
spec:
  selector:
    app: app-configuracao
  type: NodePort
  ports:
  - name: http
    port: 80 #porta exposta no service
    targetPort: 3000 #porta para qual a chamada será direcionada dentro do pod, no container
    protocol: TCP
    nodePort: 30000 #porta do pod para comunicação externa