apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: "cGcjMTIz" # o valor não pode ser em texto plano, mas sim em base64. para gerar rodar no terminal: echo "<VALOR>" | base64
  POSTGRES_USER: "a3ViZW5ld3M="
  POSTGRES_DB: "a3ViZW5ld3M="
  POSTGRES_HOST: "cG9zdGdyZXNxbA=="
